//! CLI entry point for nodesea.

use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::Parser;

/// Pure Rust Node.js Single Executable Application (SEA) builder.
///
/// Builds a standalone executable from a JavaScript source file and a Node.js
/// binary, without requiring Node.js at build time.
#[derive(Parser, Debug)]
#[command(name = "nodesea", version, about)]
struct Cli {
    /// Path to sea-config.json.
    #[arg(long)]
    config: PathBuf,

    /// Path to the Node.js binary. Defaults to `node` found in PATH.
    #[arg(long)]
    node: Option<PathBuf>,

    /// Skip macOS ad-hoc code signing.
    #[arg(long)]
    no_sign: bool,

    /// Validate config and show what would be done, without modifying files.
    #[arg(long)]
    dry_run: bool,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    // 1. Load and validate sea-config.json.
    eprintln!("[nodesea] Loading config from {}", cli.config.display());
    let config = nodesea::config::from_path(&cli.config)
        .context("failed to load sea-config.json")?;

    // 2. Resolve the config directory for relative paths.
    let config_dir = cli
        .config
        .parent()
        .unwrap_or_else(|| std::path::Path::new("."));

    // 3. Locate Node binary.
    let node_path = match cli.node {
        Some(p) => p,
        None => {
            eprintln!("[nodesea] Searching for node in PATH...");
            which::which("node").context("could not find `node` in PATH; use --node to specify")?
        }
    };
    eprintln!("[nodesea] Using node binary: {}", node_path.display());

    // 4. Detect Node version.
    let node_version = nodesea::version::detect_version(&node_path)
        .context("failed to detect Node.js version")?;
    eprintln!("[nodesea] Detected Node.js version: {node_version}");

    // 5. Determine blob version.
    let blob_version = nodesea::version::blob_version(&node_version)
        .context("failed to determine blob version")?;
    eprintln!("[nodesea] Blob format: {blob_version:?}");

    // 6. Read the main JS file.
    let main_path = config_dir.join(&config.main);
    eprintln!("[nodesea] Reading main script: {}", main_path.display());
    let main_code = std::fs::read(&main_path)
        .with_context(|| format!("failed to read main script: {}", main_path.display()))?;

    // 7. Read asset files.
    let mut asset_data: Vec<(String, Vec<u8>)> = Vec::new();
    for (name, file_path) in &config.assets {
        let full_path = config_dir.join(file_path);
        eprintln!("[nodesea] Reading asset '{name}': {}", full_path.display());
        let data = std::fs::read(&full_path)
            .with_context(|| format!("failed to read asset '{name}': {}", full_path.display()))?;
        asset_data.push((name.clone(), data));
    }

    // 8. Build flags and serialize the blob.
    let flags = config.to_flags();
    eprintln!("[nodesea] Flags: {flags:?}");

    let code_path = format!("/sea/{}", config.main);

    let assets_refs: Vec<(&str, &[u8])> = asset_data
        .iter()
        .map(|(name, data)| (name.as_str(), data.as_slice()))
        .collect();
    let assets_opt = if assets_refs.is_empty() {
        None
    } else {
        Some(assets_refs.as_slice())
    };

    let exec_argv_refs: Vec<&str> = config.exec_argv.iter().map(|s| s.as_str()).collect();
    let exec_argv_opt = if exec_argv_refs.is_empty() {
        None
    } else {
        Some(exec_argv_refs.as_slice())
    };

    eprintln!("[nodesea] Serializing SEA blob...");
    let blob = nodesea::blob::serialize(
        blob_version,
        &code_path,
        &main_code,
        flags,
        None, // code_cache: not generated by nodesea
        assets_opt,
        exec_argv_opt,
    )
    .context("failed to serialize SEA blob")?;
    eprintln!("[nodesea] Blob size: {} bytes", blob.len());

    // 9. Dry-run: print summary and exit.
    if cli.dry_run {
        eprintln!();
        eprintln!("[nodesea] === DRY RUN ===");
        eprintln!("[nodesea] Config:       {}", cli.config.display());
        eprintln!("[nodesea] Node binary:  {}", node_path.display());
        eprintln!("[nodesea] Node version: {node_version}");
        eprintln!("[nodesea] Blob format:  {blob_version:?}");
        eprintln!("[nodesea] Main script:  {}", main_path.display());
        eprintln!("[nodesea] Assets:       {}", config.assets.len());
        eprintln!("[nodesea] Blob size:    {} bytes", blob.len());
        eprintln!("[nodesea] Output:       {}", config.output);
        eprintln!(
            "[nodesea] Code signing: {}",
            if cfg!(target_os = "macos") && !cli.no_sign {
                "yes"
            } else {
                "no"
            }
        );
        eprintln!("[nodesea] No files were modified.");
        return Ok(());
    }

    // 10. Copy the Node binary to the output path.
    let output_path = config_dir.join(&config.output);
    eprintln!(
        "[nodesea] Copying {} -> {}",
        node_path.display(),
        output_path.display()
    );
    std::fs::copy(&node_path, &output_path).with_context(|| {
        format!(
            "failed to copy {} to {}",
            node_path.display(),
            output_path.display()
        )
    })?;

    // Make the output file executable on Unix.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&output_path, std::fs::Permissions::from_mode(0o755))
            .with_context(|| {
                format!(
                    "failed to set permissions on {}",
                    output_path.display()
                )
            })?;
    }

    // 11. Read the output binary, inject the blob, and write it back.
    eprintln!("[nodesea] Injecting SEA blob...");
    let mut binary = std::fs::read(&output_path)
        .with_context(|| format!("failed to read output binary: {}", output_path.display()))?;

    nodesea::inject::inject(&mut binary, &blob)
        .context("failed to inject SEA blob into binary")?;

    // 12. Flip the fuse.
    eprintln!("[nodesea] Flipping SEA fuse...");
    nodesea::fuse::flip_fuse(&mut binary).context("failed to flip SEA fuse")?;

    // Write modified binary back.
    std::fs::write(&output_path, &binary)
        .with_context(|| format!("failed to write output binary: {}", output_path.display()))?;

    // 13. Code sign on macOS (unless --no-sign).
    #[cfg(target_os = "macos")]
    {
        if !cli.no_sign {
            eprintln!("[nodesea] Ad-hoc code signing...");
            nodesea::codesign::codesign_adhoc(&output_path)
                .context("failed to ad-hoc codesign output binary")?;
        } else {
            eprintln!("[nodesea] Skipping code signing (--no-sign)");
        }
    }

    // 14. Success.
    eprintln!();
    eprintln!(
        "[nodesea] Success! Output: {}",
        output_path.display()
    );

    Ok(())
}
